### ISSUE TITLE
Atom values in where args treated as schema fields

### ISSUE THREAD

**Issue by onomated** [mathieuprog/query_builder#2]
The following query builder operation:

```elixir
args_collected_somewhere = [auth_method: :email, auth_val: "someone@example.com"]
User
|> QueryBuilder.where(args_collected_somewhere)
|> Repo.one!()
```
is resolving to the following sql and error:
```
SELECT a0.* FROM "users" AS a0 WHERE ((a0."auth_val" = $1) AND (a0."auth_method" = a0."email"))

** (Postgrex.Error) ERROR 42703 (undefined_column) column a0.email does not exist
```

This is problematic with values that are actually enums, particularly when using enum libraries such as [Ecto Enum](https://github.com/gjaldon/ecto_enum).  This behavior differs from Ecto which works as expected i.e.

```
args_collected_somewhere = [auth_method: :email, auth_val: "someone@example.com"]
User
|> Repo.get_by!(args_collected_somewhere)
```
resolves to the following SQL which executes with no errors
```
SELECT a0.* FROM "users" AS a0 WHERE ((a0."auth_val" = $1) AND (a0."auth_method" = "email"))

** (Postgrex.Error) ERROR 42703 (undefined_column) column a0.email does not exist
```

For more, see discussion in [Elixir Forum](https://elixirforum.com/t/querybuilder-compose-ecto-queries-without-effort/27704/17?u=onomated)

**Comment by mathieuprog** [comment]
I think there're three approaches:
1. check if the left atom is of type parameterized enum with `__schema__(:type, field)` (no idea what it returns as a type);
2. check if the right atom is an existing field with `__schema__(:fields)`; problem: what if the value is coincidentally the name of a field; is it worth covering that case? Therefore 1. is cleaner.
3. add new 'syntax' (as suggested in the forum with "self"), but not a fan if above solutions work.

**Comment by onomated** [comment]
1. I think specific type checking is not a good idea as different ecto types (parametized or not) may be casted from raw enums.  Basically, the schema or the developer should be able to tell true intent of the value
2. Agreed on 2, but wouldn't choose 1 as the best approach
3. New syntax here aligns with the syntax for associations, so won't really call it new.  Currently to reference fields in associations Query builder has a `<field>@<assoc_name>` syntax.  What's new with the recommendation here is having a special association name to refer to `this` i.e. self pointer.  Ultimately since the intent is for the developer to differentiate a field from a value, I think explicit specifications from the developer is the most flexible and relies on less "magic".  Maybe the syntax is not a good idea, but I would opt for my explicit intent than to try to deduce and miss the mark sometimes.

**Comment by mathieuprog** [comment]
Regarding 1., a call to `MySchema.__schema__(:type, :an_enum_field)` gives something like:

```elixir
{:parameterized, Ecto.Enum,
 %{
   on_dump: %{
     # ...
   },
   on_load: %{
     # ...
   },
   type: :string,
   values: [
      # ...
   ]
 }}
 ```

We can clearly detect an `Ecto.Enum` with its values.

> different ecto types (parametized or not) may be casted from raw enums

I didn't understand that.

What do you think?

3. is not bad with your further explanations. I agree with the magic part.

**Comment by onomated** [comment]
> Regarding 1., a call to `MySchema.__schema__(:type, :an_enum_field)` gives something like:
> 
> ```elixir
> {:parameterized, Ecto.Enum,
>  %{
>    on_dump: %{
>      # ...
>    },
>    on_load: %{
>      # ...
>    },
>    type: :string,
>    values: [
>       # ...
>    ]
>  }}
> ```
> 
> We can clearly detect an `Ecto.Enum` with its values.
> 
> > different ecto types (parametized or not) may be casted from raw enums
> 
> I didn't understand that.
> 
> What do you think?

So that logic works with `Ecto.Enum` but there can be another custom Ecto type that can be casted from an enum.  So I may have something like this:

```elixir
defmodule MyApp.Types.Color do
  use Ecto.Type

  def type, do: :string

  def cast(:red), do: "0xFF0000"
  def cast(:green), do: "0x00FF00"
  def cast(:blue), do: "0x0000FF"
  def cast(string) when is_binary(string), do: ColorUtils.parse(string)
  def cast(_), do: :error

  def load(string) when is_binary(string),
    do: ColorUtils.parse(string)
end
```
In this case, enum values can also be passed to `QueryBuilder` but not as a result of using `Ecto.Enum`

**Comment by mathieuprog** [comment]
Ahh right atoms as values are not limited to `Ecto.Enum`. Haha obviously.

Let's go for `@self`. It's actually brilliant to come up with such an idea :-O

**Comment by onomated** [comment]
Sounds good!  I'll fork this repo and submit a PR when I have a working, tested solution.  One last suggestion if you want to avoid this `<field>@self` syntax is to use `%{field: _field, schema: :self}`, then we just pattern match on that.  Maybe even extend that to the association syntax today.

Not as clean imo.  I like the simplicity of the existing syntax, but thought I'd throw out there if the syntax still isn't gelling with you

**Comment by mathieuprog** [comment]
let's go for `@self` 👍
