### ISSUE TITLE
Provide easy customization/extendability to existing QueryBuilder functions

### ISSUE THREAD

**Issue by onomated** [mathieuprog/query_builder#3]
Provide an easy way for clients to extend the functionality and add new app specific query functionality.  While still being able to utilize `from_list` functionality.

See the full convo on [Elixir Forum](https://elixirforum.com/t/querybuilder-compose-ecto-queries-without-effort/27704/20?u=onomated).

**Comment by mathieuprog** [comment]
Did you want to submit a PR for that?

**Comment by onomated** [comment]
Yes. This is coming up next.

**Comment by onomated** [comment]
@mathieuprog:  https://github.com/mathieuprog/query_builder/pull/5

**Comment by mathieuprog** [comment]
Nice 👍 left a comment.

**Comment by mathieuprog** [comment]
Do you think that we should make a 1.0 version now because of the change for `order_by`?
https://elixirforum.com/t/27704/12
Can we consider it enough stable for a 1.0?

**Comment by onomated** [comment]
That would be my vote.  Works like a charm and programmatic interface is set and feels complete.  No interface breaking in a while outside of `order_by` which matches the ecto query api interface now

**Comment by mathieuprog** [comment]
When trying to publish a new version, I got the following error:


Building docs...
** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {{:to_query, 1}, [{:type, 9, :fun, [{:type, 9, :product, [{:user_type, 9, :t, []}]}, {:type, 9, :term, []}]}]}
    (elixir 1.12.3) lib/keyword.ex:475: Keyword.keys/1
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:385: anonymous fn/2 in ExDoc.Retriever.get_impls/1
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:384: ExDoc.Retriever.get_impls/1
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:164: ExDoc.Retriever.get_module_data/2
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:115: ExDoc.Retriever.generate_node/3
    (elixir 1.12.3) lib/enum.ex:3900: Enum.flat_map_list/2
    (ex_doc 0.21.2) lib/ex_doc/retriever.ex:43: ExDoc.Retriever.docs_from_modules/2


First time that happens for me. Looking into it.

**Comment by mathieuprog** [comment]
Updated ex_doc, now it works
